apiVersion: v1
kind: Namespace
metadata:
  name: ns-juan-rojas

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-juan-rojas
  namespace: ns-juan-rojas
data:
  AMBIENTE: "DESARROLLO"

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-juan-rojas
  namespace: ns-juan-rojas
type: Opaque
stringData:
  API_KEY: "123456789"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-juan-rojas
  namespace: ns-juan-rojas

spec:
  replicas: 2

  selector:
    matchLabels:
      app: app-juan-rojas

  template:
    metadata:
      labels:
        app: app-juan-rojas

    spec:
      containers:
        - name: app
          image: jarojaslv/lab3:juan-rojas

          ports:
            - containerPort: 3000

          env:
            - name: AMBIENTE
              valueFrom:
                configMapKeyRef:
                  name: config-juan-rojas
                  key: AMBIENTE

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-juan-rojas
                  key: API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: svc-juan-rojas
  namespace: ns-juan-rojas

spec:
  selector:
    app: app-juan-rojas

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP
